### ISSUE TITLE
Ollama models does not appear on the web browser plugin dropdown after installing Ollama plugin

### ISSUE THREAD

**Issue by sears2424** [Crivella/ocr_translate-ollama#1]
`ERROR (400): Failed to make request to ollama: {"error":"neither 'from' or 'files' was specified"}
[X](moz-extension://71c41173-4992-4fb0-b248-94a3829e9bb8/popup.html#)`

appears when trying out `llama3:8b`

and other ollama models that are present on my machine doesnt appear on the model dropdown.

things I tried:

1. verified ollama is running 
2. set run-user.bat to

```
@echo off

set OCT_VERSION=0.6.1
set OCT_AUTOUPDATE=

set LOAD_ON_START=

set DEVICE=cuda
set OCT_BASE_DIR=
set DATABASE_NAME=

set DJANGO_DEBUG=true
set DJANGO_LOG_LEVEL=INFO

set OLLAMA_ENDPOINT=http://localhost:11434/api

call run.bat
```

**Comment by sears2424** [comment]
Adding the model name manually on the database allowed me to use custom models

**Comment by Crivella** [comment]
I will look into this.

Was the `llama3:8b` model appearing like this or as `oct_ollama_llama3:8b` ?

By default the plugins prepend the content of the `MODEL_NAME_PREFIX` environment variable [CODE](https://github.com/Crivella/ocr_translate-ollama/blob/8433375e93b87ea406e819458833031d6b0b4286/ocr_translate_ollama/commons.py#L28) (or `oct_ollama_` if not found) as it creates a new model using the original model as  a base with a new system prompt specifying the [format in which the translations/response should be handled](https://github.com/Crivella/ocr_translate-ollama/blob/8433375e93b87ea406e819458833031d6b0b4286/ocr_translate_ollama/commons.py#L31)

In your case are you adding the bare Ollama model names to the database or using the prefix? In the former case i've not tested how ollama handles creating multiple models with the same name but with a different system prompt (not sure if the original is being replaced or what).

Also if you still have the logs shown by the server when this happened it would help me pinpoint the problem.

PS: the plugin by default will only wrap around `llama3:8b` it is not set to automatically detect what models you have on your ollama server (the model added to the server are dictated by the [entrypoints](https://github.com/Crivella/ocr_translate-ollama/blob/8433375e93b87ea406e819458833031d6b0b4286/pyproject.toml#L44) and the [model data](https://github.com/Crivella/ocr_translate-ollama/blob/8433375e93b87ea406e819458833031d6b0b4286/ocr_translate_ollama/__init__.py#L25))

**Comment by sears2424** [comment]
The model is appearing as `oct_ollama_llama3:8b`. thats what the init script does iirc. but both the model detection portion of the plugin and the download-and-rename portion doesnt work as intended (no custom models on the drop-down list, and when i downloaded `oct_ollama_llama3:8b` anyway, it results on the error above)

**Comment by sears2424** [comment]
I am adding the bare ollama model names on the database yes, to use them

**Comment by Crivella** [comment]
Been busy lately but finally managed to have a look at this, but was not able to reproduce it.

Is there something that might be blocking the creation of new models for you?
Will probably need the logs of the server with debug mode on in order to understand what is happening.

In my case I started with a compose clean install (file at the end) and the renamed version of llama3:8b seems to be created and used correctly

```log
oct_server    | 2025-03-11 10:50:00,537 -    INFO -     ocr.general:tsl             - Loading TSL model: oct_ollama_llama3:8b
oct_server    | 2025-03-11 10:50:00,538 -   DEBUG -     ocr.general:models          - Loading model oct_ollama_llama3:8b from entrypoint ocr_translate.tsl_models:ollama.tsl
oct_ollama    | [GIN] 2025/03/11 - 10:50:00 | 200 |     1.71626ms |      172.24.0.4 | GET      "/api/tags"
oct_server    | 2025-03-11 10:50:00,546 -    INFO -          plugin:plugin          - Model oct_ollama_llama3:8b not found in ollama, attempting download...
oct_ollama    | time=2025-03-11T10:50:01.293Z level=INFO source=download.go:136 msg="downloading 6a0746a1ec1a in 47 100 MB part(s)"
oct_ollama    | time=2025-03-11T10:50:28.294Z level=INFO source=download.go:251 msg="6a0746a1ec1a part 23 stalled; retrying. If this persists, press ctrl-c to exit, then 'ollama pull' to find a faster connection."
oct_ollama    | time=2025-03-11T10:50:42.514Z level=INFO source=download.go:136 msg="downloading 4fa551d4f938 in 1 12 KB part(s)"
oct_ollama    | time=2025-03-11T10:50:43.732Z level=INFO source=download.go:136 msg="downloading 8ab4849b038c in 1 254 B part(s)"
oct_ollama    | time=2025-03-11T10:50:44.945Z level=INFO source=download.go:136 msg="downloading 577073ffcc6c in 1 110 B part(s)"
oct_ollama    | time=2025-03-11T10:50:46.161Z level=INFO source=download.go:136 msg="downloading 3f8eb4da87fa in 1 485 B part(s)"
oct_ollama    | [GIN] 2025/03/11 - 10:50:51 | 200 | 51.069062782s |      172.24.0.4 | POST     "/api/pull"
oct_server    | 2025-03-11 10:50:51,616 -    INFO -          plugin:plugin          - Model oct_ollama_llama3:8b downloaded successfully.
oct_server    | 2025-03-11 10:50:51,617 -    INFO -          plugin:plugin          - Creating model with system prompt for translation.
oct_ollama    | [GIN] 2025/03/11 - 10:50:51 | 200 |   17.682332ms |      172.24.0.4 | POST     "/api/create"
```

Image from the extension popup

![Image](https://github.com/user-attachments/assets/10c555b7-928c-486b-b473-3e021c0f7c45)

Image from Open-webui
![Image](https://github.com/user-attachments/assets/b3e930c0-419a-49dd-894c-2f27f6d234db)

And the model is being used coorectly

```
oct_server      | 2025-03-11 11:00:27,959 -   DEBUG -          plugin:plugin          - Translating text with request data `{'model': 'oct_ollama_llama3:8b', 'prompt': 'src="japanese"\ndst="english"\ncontext=""\ntext="[いてーム】 4必2心孝 の9還必全 "', 'stream': False}`.
oct_open-webui  | INFO:     127.0.0.1:47244 - "GET /health HTTP/1.1" 200 OK
oct_ollama      | llama_new_context_with_model: n_ctx      = 8192
oct_ollama      | llama_new_context_with_model: n_batch    = 512
oct_ollama      | llama_new_context_with_model: n_ubatch   = 512
oct_ollama      | llama_new_context_with_model: flash_attn = 0
oct_ollama      | llama_new_context_with_model: freq_base  = 500000.0
oct_ollama      | llama_new_context_with_model: freq_scale = 1
oct_ollama      | llama_kv_cache_init:        CPU KV buffer size =  1024.00 MiB
oct_ollama      | llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
oct_ollama      | llama_new_context_with_model:        CPU  output buffer size =     2.02 MiB
oct_ollama      | llama_new_context_with_model:        CPU compute buffer size =   560.01 MiB
oct_ollama      | llama_new_context_with_model: graph nodes  = 1030
oct_ollama      | llama_new_context_with_model: graph splits = 1
oct_ollama      | INFO [main] model loaded | tid="135046749022080" timestamp=1741690863
oct_ollama      | time=2025-03-11T11:01:03.183Z level=INFO source=server.go:622 msg="llama runner started in 35.14 seconds"
oct_ollama      | [GIN] 2025/03/11 - 11:01:13 | 200 | 45.268622629s |      172.24.0.4 | POST     "/api/generate"
oct_server      | 2025-03-11 11:01:13,231 -   DEBUG -          plugin:plugin          - Received response from ollama: {'model': 'oct_ollama_llama3:8b', 'created_at': '2025-03-11T11:01:13.148755139Z', 'response': '"[
```

This is the `compose.yml` file I used

```yml
name: ocr_translate

volumes:
  ollama:
  open-webui:
  plugins:
  models:
  database:

services:
  server:
    container_name: oct_server
    image: crivella1/ocr_translate:0.6.1
    volumes:
      - plugins:/plugin_data
      - models:/models
    env_file:
      - .env
    environment:
      - LOAD_ON_START=last
      - DJANGO_DEBUG=true
      - DJANGO_LOG_LEVEL=DEBUG

      - DATABASE_NAME=${DB_DATABASE_NAME}
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=database
      - DATABASE_PORT=5432

      - OCT_OLLAMA_ENDPOINT=http://ollama:11434/api
    ports:
      - 4000:4000
    depends_on:
      - database
    restart: unless-stopped

  database:
    container_name: oct_postgres
    image: postgres:16.4
    # user: ${UID}:${GID}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: oct_ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: oct_open-webui
    ports:
      - 3000:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
  

```
